GET http://localhost:3001/api/products

###
GET http://localhost:3001/api/categories

###
POST http://localhost:3001/api/categories
Content-Type: application/json

{
  "name": "Nueva categoría",
  "description": "Categoría de prueba para testeo"
}
